### ISSUE TITLE
Breaking change for fastlane in 0.16.1

### ISSUE THREAD

**Issue by janpio** [lostisland/faraday#1036]
(Note: Read all the comments first before thinking about the actual problems, possible this here in the issue itself is not the real problem or error)

## Basic Info

* Faraday Version: 0.16.1
* Ruby Version: 2.3

## Issue description

[fastlane](https://github.com/fastlane/fastlane) is using faraday (and after breaking on error classes in general with 0.16.0 which fortunately were quickly fixed by 0.16.1) we are encountering new problems with 0.16.1 when running our tests:

```
  1) Spaceship::Client retry re-raises when retry limit reached throwing Faraday::TimeoutError
     Failure/Error:
       stub_request(:get, test_uri).
         to_raise(error).times(times).then.
         to_return(status: status, body: body)

     NoMethodError:
       undefined method `to_ary' for Faraday::TimeoutError:Class
     # ./.bundle/ruby/2.3.0/gems/faraday-0.16.1/lib/faraday/deprecated_constant.rb:42:in `method_missing'
     # ./.bundle/ruby/2.3.0/gems/webmock-2.3.2/lib/webmock/request_stub.rb:32:in `flatten'
     # ./.bundle/ruby/2.3.0/gems/webmock-2.3.2/lib/webmock/request_stub.rb:32:in `to_raise'
     # ./spaceship/spec/client_spec.rb:34:in `stub_client_request'
     # ./spaceship/spec/client_spec.rb:108:in `block (4 levels) in <top (required)>'
```

https://circleci.com/gh/fastlane/fastlane/35752

I am not a ruby developer, so I might be missing something really obvious here - please let me know if this is the case. From my naive understanding, it might be that https://github.com/lostisland/faraday/pull/1030 did not at back _all_ the previous behavior (that fastlane unfortunately relies on).

(This is _not_ happening with Ruby 2.5 which we are also testing.)

**Comment by janpio** [comment]
To add on the fun, we are also testing on Windows with `ruby 2.4.6p354 (2019-04-01 revision 67394) [x64-mingw32]`. There the same tests are failing, but with different error messages:

```
  1) Spaceship::Client retry re-raises when retry limit reached throwing Faraday::TimeoutError
     Failure/Error:
       expect do
         subject.req_home
       end.to raise_error(thrown)
       expected Faraday::TimeoutError, got #<RuntimeError: can't modify frozen String> with backtrace:
         # ./spaceship/lib/spaceship/client.rb:811:in `force_encoding'
         # ./spaceship/lib/spaceship/client.rb:811:in `log_response'
         # ./spaceship/lib/spaceship/client.rb:846:in `block in send_request'
         # ./spaceship/lib/spaceship/client.rb:620:in `with_retry'
         # ./spaceship/lib/spaceship/client.rb:844:in `send_request'
         # ./spaceship/lib/spaceship/client.rb:688:in `request'
         # ./spaceship/spec/client_spec.rb:8:in `req_home'
         # ./spaceship/spec/client_spec.rb:111:in `block (5 levels) in <top (required)>'
         # ./spaceship/spec/client_spec.rb:110:in `block (4 levels) in <top (required)>'
     # ./spaceship/spec/client_spec.rb:110:in `block (4 levels) in <top (required)>'
  2) Spaceship::Client retry retries when Faraday::TimeoutError error raised
     Failure/Error: request(:get, TestClient.hostname)
     RuntimeError:
       can't modify frozen String
     # ./spaceship/lib/spaceship/client.rb:811:in `force_encoding'
     # ./spaceship/lib/spaceship/client.rb:811:in `log_response'
     # ./spaceship/lib/spaceship/client.rb:846:in `block in send_request'
     # ./spaceship/lib/spaceship/client.rb:620:in `with_retry'
     # ./spaceship/lib/spaceship/client.rb:844:in `send_request'
     # ./spaceship/lib/spaceship/client.rb:688:in `request'
     # ./spaceship/spec/client_spec.rb:8:in `req_home'
     # ./spaceship/spec/client_spec.rb:118:in `block (4 levels) in <top (required)>'
```

https://ci.appveyor.com/project/KrauseFx/fastlane/builds/27733501

**Comment by janpio** [comment]
Ahem, we are now also seeing test failures with Ruby 2.5 (and not on Ruby 2.3 any more):

```
  1) Spaceship::Client retry re-raises when retry limit reached throwing Faraday::TimeoutError
     Failure/Error:
       expect do
         subject.req_home
       end.to raise_error(thrown)

       expected Faraday::TimeoutError, got #<FrozenError: can't modify frozen String> with backtrace:
         # ./spaceship/lib/spaceship/client.rb:811:in `force_encoding'
         # ./spaceship/lib/spaceship/client.rb:811:in `log_response'
         # ./spaceship/lib/spaceship/client.rb:846:in `block in send_request'
         # ./spaceship/lib/spaceship/client.rb:620:in `with_retry'
         # ./spaceship/lib/spaceship/client.rb:844:in `send_request'
         # ./spaceship/lib/spaceship/client.rb:688:in `request'
         # ./spaceship/spec/client_spec.rb:8:in `req_home'
         # ./spaceship/spec/client_spec.rb:111:in `block (5 levels) in <top (required)>'
         # ./spaceship/spec/client_spec.rb:110:in `block (4 levels) in <top (required)>'
     # ./spaceship/spec/client_spec.rb:110:in `block (4 levels) in <top (required)>'

  2) Spaceship::Client retry retries when Faraday::TimeoutError error raised
     Failure/Error: request(:get, TestClient.hostname)

     FrozenError:
       can't modify frozen String
     # ./spaceship/lib/spaceship/client.rb:811:in `force_encoding'
     # ./spaceship/lib/spaceship/client.rb:811:in `log_response'
     # ./spaceship/lib/spaceship/client.rb:846:in `block in send_request'
     # ./spaceship/lib/spaceship/client.rb:620:in `with_retry'
     # ./spaceship/lib/spaceship/client.rb:844:in `send_request'
     # ./spaceship/lib/spaceship/client.rb:688:in `request'
     # ./spaceship/spec/client_spec.rb:8:in `req_home'
     # ./spaceship/spec/client_spec.rb:118:in `block (4 levels) in <top (required)>'
```

https://circleci.com/gh/fastlane/fastlane/35783

Totally not clear to me why this is happening, doesn't make sense to me. But the error messages here are consitent to the ones we are seeing on Windows - so maybe the first one was a fluke or... I have no idea seriously 🤷‍♀
