### ISSUE TITLE
regression with 2.5.1: ArgumentError: unknown keyword

### ISSUE THREAD

**Issue by rocket-turtle** [lostisland/faraday#1444]
## Basic Info

* Faraday Version: faraday-2.5.1
* Ruby Version: ruby-2.7.6

## Issue description

With the new Version I get an ruby deprecation and my test is failing:

```
../faraday-2.5.1/lib/faraday/adapter/test.rb:287: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
../faraday-2.5.1/lib/faraday/adapter.rb:62: warning: The called method `save_response' is defined here
    returns a predefined response (FAILED - 1)

Failures:

  1) Test::Client#disabled_api_connection returns a predefined response
     Failure/Error: response = connection.get('')

     ArgumentError:
       unknown keyword: :"Content-Type"
     # ../faraday-2.5.1/lib/faraday/adapter.rb:62:in `save_response'
     # ../faraday-2.5.1/lib/faraday/adapter/test.rb:287:in `call'
     # ../faraday-2.5.1/lib/faraday/rack_builder.rb:153:in `build_response'
     # ../faraday-2.5.1/lib/faraday/connection.rb:445:in `run_request'
     # ../faraday-2.5.1/lib/faraday/connection.rb:200:in `get'
     # ../spec/models/test/client_spec.rb:323:in `block (3 levels) in <top (required)>'
```

I think the Problem is that https://github.com/lostisland/faraday/commit/6799f5852d31dae32699949790633c68282ab71d added an keyword parameter to save_response and now the headers from _lib/faraday/adapter.rb:62_ are splitted into the arguments and cause the Problem.

## Steps to reproduce
I do not know why the tests for the Adapter do not show the same error. I can investigate further if you can not reproduce the error.
