### ISSUE TITLE
Status Message

### ISSUE THREAD

**Issue by BaneOfSerenity** [lostisland/faraday#590]
While using Faraday I noticed that the status code is in the response.status but there is no way to get the status message. When looking at my VCR cassette there is a code and a message being sent back. It would be nice to be able to access this message especially for 4xx and 5xx returns. Also it seem the message is being thrown out early on as it doesn't show up in the response.env either.
```
  response:
    status:
      code: 403
      message: Forbidden
    headers:
      Content-Type:
      - application/json
```
